#ifndef PROCESSING_H
#define PROCESSING_H

#pragma once

/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

uint64_t processing_add(uint64_t left, uint64_t right);

#endif  /* PROCESSING_H */
