name: 🐛 Found a Bug
description: Report broken or incorrect behavior in Processing 4. (For help with your own code, please visit our forum at discourse.processing.org instead).
labels: [bug]
body:


- type: dropdown
  id: sub-area
  attributes:
    label: Most appropriate sub-area of Processing 4?
    description: You may select more than one.
    multiple: true
    options:
        - I'm not sure
        - Accessibility
        - Core/Environment/Rendering
        - PDE
        - Data
        - Events
        - Image
        - IO
        - Math
        - Typography
        - Utilities
        - OpenGL
        - Contributions Manager
        - Export
        - Build process
        - Unit testing
        - Internationalization
        - Other (specify if possible)
  validations:
    required: true

- type: input
  attributes:
    label: Processing version
    description: Go to "Help > About Processing" and look in the bottom-right corner for the version number.
  validations:
    required: true

- type: input
  attributes:
    label: Operating system
    description: "Ex: Windows/MacOSX/Linux/Android/iOS along with version"
  validations:
    required: true

- type: textarea
  attributes:
    label: Bug description
    description: |
      Describe the bug in detail. Include what you expected to happen and what actually happened.
      If applicable, include any error messages you received.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce this
    description: Describe what steps will produce the bug.
    value: |
      "1.

      2.

      3."
  validations:
    required: true

- type: textarea
  attributes:
    label: snippet
    description: If applicable, include a minimal sketch that produces the error.
    value: |
      ```processing

      // Paste your code below :)

      void setup() {

      }

      void draw() {

      }
      ```
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional context
    description: Provide any other information, links, or screenshots that could help illustrate the bug.
  validations:
    required: false

- type: dropdown
  attributes:
    label: Would you like to work on the issue?
    description: |
      If not, that’s okay too. Your report is appreciated.
    options:
      - No, I’m just reporting the issue
      - Yes, I’d like to help with this
      - I’m not sure yet
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      > [!NOTE]
      > Processing is a community-driven, open-source project. If you have time and interest to help, your contribution would be greatly appreciated! See the [contribution guide](https://github.com/processing/processing4/blob/main/CONTRIBUTING.md) to learn more. And if you need some guidance or support, we're happy to help you get started.