name: 💡 Existing Feature Enhancement
description: Suggest an improvement for an existing feature of Processing.
labels: [enhancement]
body:

- type: dropdown
  id: feature-area
  attributes:
    label: Most relevant area for this enhancement?
    description: Choose the most relevant area for the proposed feature or improvement.
    multiple: true
    options:
        - Accessibility
        - Core/Environment/Rendering
        - PDE
        - Data
        - Events
        - Image
        - IO
        - Math
        - Typography
        - Utilities
        - OpenGL
        - Contributions Manager
        - Export
        - Build process
        - Unit testing
        - Internationalization
        - Other (specify if possible)
  validations:
    required: true

- type: input
  attributes:
    label: Feature to enhance
    description: Which existing feature of Processing would be improved by this enhancement?
  validations:
    required: true

- type: textarea
  attributes:
    label: Desired enhancement
    description: Describe the improvement you’d like to see with that existing feature
  validations:
    required: true

- type: textarea
  attributes:
    label: Potential benefits
    description: Explain how this enhancement could benefit users or improve Processing.
  validations:
    required: false

- type: textarea
  attributes:
    label: Possible drawbacks
    description: Consider any possible drawbacks or challenges related to the implementation of this enhancement.
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false

- type: dropdown
  attributes:
    label: Would you like to help implement this enhancement?
    description: |
      Note: [creating a library](https://github.com/processing/processing4/blob/main/CONTRIBUTING.md#adding-new-features-to-processing) is often the best way to add new features to Processing. If you’re suggesting a change that could be implemented as a library, please consider that approach first.

      If you’re interested in helping implement this enhancement, let us know below. We’re happy to provide guidance and support. If not, your suggestion is still valuable and appreciated.
    options:
      - No, I’m just suggesting the enhancement
      - Yes, I’d like to help with this
      - I’m not sure yet
  validations:
    required: true