name: 🌱 New Feature Request
description: Request adding a new feature to Processing
labels: [new feature]
body:

- type: dropdown
  id: feature-area
  attributes:
    label: Relevant sub-area for this feature?
    description: Choose the sub-area most relevant to your feature request.
    multiple: true
    options:
      - Accessibility
      - Core/Environment/Rendering
      - PDE
      - Data
      - Events
      - Image
      - IO
      - Math
      - Typography
      - Utilities
      - OpenGL
      - Contributions Manager
      - Export
      - Build process
      - Unit testing
      - Internationalization
      - Other (specify if possible)
  validations:
    required: true

- type: textarea
  id: feature-description
  attributes:
    label: Feature description
    description: Describe the feature in detail. Include how it should work and its intended impact.
  validations:
    required: true

- type: textarea
  id: benefits
  attributes:
    label: Benefits
    description: Outline how this feature would benefit users or improve Processing.
  validations:
    required: true

- type: textarea
  id: challenges
  attributes:
    label: Possible challenges
    description: Discuss any possible challenges or considerations in implementing this feature.
  validations:
    required: false

- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: Provide any other information, links, or screenshots that could help illustrate the feature.
  validations:
    required: false

- type: dropdown
  attributes:
    label: Would you like to help implement this feature?
    description: |
      Note: [creating a library](https://github.com/processing/processing4/blob/main/CONTRIBUTING.md#adding-new-features-to-processing) is often the best way to add new features to Processing. If you’re suggesting a feature that could be implemented as a library, please consider that approach first.

      If you’re interested in helping implement this feature, let us know below. We’re happy to provide guidance and support. If not, your suggestion is still valuable and appreciated.
    options:
      - No, I’m just suggesting the feature
      - Yes, I’d like to help with this
      - I’m not sure yet
  validations:
    required: true
