name: 🌱 New Feature Request
description: Request adding a new feature to Processing
labels: [new feature]
body:

- type: dropdown
  id: feature-area
  attributes:
    label: Relevant sub-area for this feature?
    description: Choose the sub-area most relevant to your feature request.
    multiple: true
    options:
      - Accessibility
      - Core/Environment/Rendering
      - PDE
      - Data
      - Events
      - Image
      - IO
      - Math
      - Typography
      - Utilities
      - OpenGL
      - Contributions Manager
      - Export
      - Build process
      - Unit testing
      - Internationalization
      - Other (specify if possible)
  validations:
    required: true

- type: textarea
  id: feature-description
  attributes:
    label: Feature description
    description: Describe the feature in detail. Include how it should work and its intended impact.
  validations:
    required: true

- type: textarea
  id: benefits
  attributes:
    label: Benefits
    description: Outline how this feature would benefit users or improve Processing.
  validations:
    required: true

- type: textarea
  id: challenges
  attributes:
    label: Possible challenges
    description: Discuss any possible challenges or considerations in implementing this feature.
  validations:
    required: false

- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: Provide any other information, links, or screenshots that could help illustrate the feature.
  validations:
    required: false

- type: dropdown
  attributes:
    label: Would you like to work on the issue?
    description: |
      Thank you for reporting this issue! Processing is a community-driven, open-source project. That means issues like this often rely on contributors like you to help investigate and fix them.

      Let us know if you’d like to try fixing it yourself, and don’t worry, we can guide you through the process. If not, that’s okay too. Your report is appreciated.

      See [CONTRIBUTING.md](https://github.com/processing/processing4/blob/main/CONTRIBUTING.md) to learn more about how to get involved.
    options:
      - Yes, I’d like to help with this
      - No, I’m just reporting the issue
      - I’m not sure yet
  validations:
    required: true